# This file is only for the purpose of testing.
# It should not be used in the production environment.

include "constant.conf";

define POP_REGION = 999;
define POP_COUNTRY = 999;
define POP_LOCAL = 999;

define POP_KERNEL_EXPORT = true;
define POP_KERNEL_PREFSRC = 255.255.255.255;

router id 255.255.255.255;

protocol static {
	ipv6;
}

function local_export_config() -> bool {
	return true;
}

include "loader.conf";

# include "session/*.conf";
