function downstream_import_filter(int ASN) -> bool {
	if is_invalid() then return false;
	lc_add_in(ASN, 2);
	if !is_downstream_asn() then return false;

	case net.type {
		NET_IP4: {
			if ASN !~ ASN_DOWNSTREAM then return false;
			if (ASN = 203031) then return (net ~ DOWNSTREAM_PREFIXES_AS203031_IPV4) || (net ~ DOWNSTREAM_PREFIXES_AS203031_CUSTOM_IPV4);
			if (ASN = 211575) then return (net ~ DOWNSTREAM_PREFIXES_AS211575_IPV4) || (net ~ DOWNSTREAM_PREFIXES_AS211575_CUSTOM_IPV4);
			if (ASN = 214933) then return (net ~ DOWNSTREAM_PREFIXES_AS214933_IPV4) || (net ~ DOWNSTREAM_PREFIXES_AS214933_CUSTOM_IPV4);
			return false;
		}
		NET_IP6: {
			if ASN !~ ASN_DOWNSTREAM then return false;
			if (ASN = 203031) then return (net ~ DOWNSTREAM_PREFIXES_AS203031_IPV6) || (net ~ DOWNSTREAM_PREFIXES_AS203031_CUSTOM_IPV6);
			if (ASN = 211575) then return (net ~ DOWNSTREAM_PREFIXES_AS211575_IPV6) || (net ~ DOWNSTREAM_PREFIXES_AS211575_CUSTOM_IPV6);
			if (ASN = 214933) then return (net ~ DOWNSTREAM_PREFIXES_AS214933_IPV6) || (net ~ DOWNSTREAM_PREFIXES_AS214933_CUSTOM_IPV6);
			return false;
		}
		else: {
			print "downstream_import_filter: unexpected net.type ", net.type, " ", net;
			return false;
		}
	}
}
