function transit_import_filter(int ASN) -> bool {
    if is_invalid() then return false;
    lc_add_in(ASN, 1);
    bgp_local_pref = 100;
    return true;
}

function transit_export_filter(int ASN) -> bool {
    if source !~ [ RTS_BGP, RTS_STATIC, RTS_DEVICE ] then return false;
    if is_invalid() then return false;
    if bgp_large_community ~ [(ASN_LOCAL, 110, 1), (ASN_LOCAL, 110, 3), (ASN_LOCAL, 110, 4)] then return false;
    if (!is_self_route() && !is_downstream_route()) then return false;
    return lc_export(ASN);
}

function downstream_export_filter(int ASN) -> bool {
    if source !~ [ RTS_BGP, RTS_STATIC, RTS_DEVICE ] then return false;
    if is_invalid() then return false;
    return true;
}

function ixp_import_filter(int ASN) -> bool {
    if is_invalid() then return false;
    lc_add_in(ASN, 3);
    bgp_local_pref = 100;
    return true;
}

function ixp_export_filter(int ASN) -> bool {
    if source !~ [ RTS_BGP, RTS_STATIC, RTS_DEVICE ] then return false;
    if is_invalid() then return false;
    if bgp_large_community ~ [(ASN_LOCAL, 110, 1), (ASN_LOCAL, 110, 3), (ASN_LOCAL, 110, 4)] then return false;
    if (!is_self_route() && !is_downstream_route()) then return false;
    lc_export(ASN);
    return true;
}

function peer_import_filter(int ASN) -> bool {
    if is_invalid() then return false;
    lc_add_in(ASN, 4);
    return true;
}

function peer_export_filter(int ASN) -> bool {
    if source !~ [ RTS_BGP, RTS_STATIC, RTS_DEVICE ] then return false;
    if is_invalid() then return false;
    if bgp_large_community ~ [(ASN_LOCAL, 110, 1), (ASN_LOCAL, 110, 3), (ASN_LOCAL, 110, 4)] then return false;
    if (!is_self_route() && !is_downstream_route()) then return false;
    lc_export(ASN);
    return true;
}

function collector_export_filter() -> bool {
    if is_invalid() then return false;
    return true;
}

function rr_filter() -> bool {
    if source !~ [ RTS_BGP, RTS_STATIC, RTS_DEVICE ] then return false;
    if is_invalid() then return false;
    return true;
}
