# LOA Provided Prefixes
define DOWNSTREAM_PREFIXES_AS211575_CUSTOM_IPV4 = [
];

define DOWNSTREAM_PREFIXES_AS211575_CUSTOM_IPV6 = [
];

define DOWNSTREAM_PREFIXES_AS203031_CUSTOM_IPV4 = [
    193.0.14.0/23,
	193.0.14.0/24,
	193.0.15.0/24,
	193.0.8.0/23,
    193.0.8.0/24,
    193.0.9.0/24
];

define DOWNSTREAM_PREFIXES_AS203031_CUSTOM_IPV6 = [
    2001:7fd::/32,
    2001:7fd::/48,
    2001:7fd:ffff::/48,
    2a13:27c0:30::/44,
    2a13:27c0:30::/48,
    2a13:27c0:3f::/48
];

define DOWNSTREAM_PREFIXES_AS214933_CUSTOM_IPV4 = [
];

define DOWNSTREAM_PREFIXES_AS214933_CUSTOM_IPV6 = [
];