protocol device {
    scan time 10;
}

protocol direct {
	interface "dummy*", "igp-*";
	ipv4;
	ipv6;
}

function kernel_export_filter() -> bool {
	if source !~ [RTS_BGP, RTS_STATIC] then return false;
	if is_default_route() then return true;
	if is_self_route() then return true;
	# if is_downstream_route() then return true;
	return false;
}

filter kernel_export {
	if POP_KERNEL_EXPORT then {
		if POP_KERNEL_PREFSRC != 255.255.255.255 then {
			krt_prefsrc = POP_KERNEL_PREFSRC;
			accept;
		}
		accept;
	}
	kernel_export_filter();
}

protocol kernel {
	learn;
    ipv6 { 
		import all; 
		export filter kernel_export;
	};
}
