roa4 table rpki4;
roa6 table rpki6;

protocol rpki rpki_cf {
    roa4 {
        table rpki4;
    };
    roa6 {
        table rpki6;
    };
    # CloudFlare RPKI Server
    remote "172.65.0.2" port 8282;
    # Retry Every Minute
    retry keep 60;
    # Refresh Every Hour
    refresh keep 3600;
    # Expire Every 8 Hours
    expire 28800;
    transport tcp; 
}

function is_invalid_rpki() -> bool { 
    case net.type {
        NET_IP4: return roa_check(rpki4, net, bgp_path.last) = ROA_INVALID;
        NET_IP6: return roa_check(rpki6, net, bgp_path.last) = ROA_INVALID;
        else: {
            print "is_invalid_rpki: unexpected net.type ", net.type, " ", net;
            return false;
        }
    }
}
