template bgp pub_bgp_v6 {
	local as ASN_LOCAL;
	graceful restart on;
	ipv6 {
		export limit 10;
	};
}

template bgp pub_bgp_v4 {
	local as ASN_LOCAL;
	graceful restart on;
	ipv4 {
		export limit 0;
	};
}

template bgp pub_collector {
	local as ASN_LOCAL;
	graceful restart on;
	interpret communities off;
	ipv6 {
		import limit 0;
	};
}

template bgp int_bgp_v6 {
	local as ASN_LOCAL;
	graceful restart on;
	direct;
	ipv6 {
		next hop self;
		gateway direct;
	};
}

template bgp int_rr_v6 {
	local as ASN_LOCAL;
	graceful restart on;
	ipv6 {
		import all;
		export where rr_filter();
	};
}
